CREATE DATABASE customer_behavior;
USE customer_behavior;
SELECT * FROM customer_shopping_behavior LIMIT 20;

-- total revenue generated by male vs female
SELECT gender , SUM(purchase_amount) AS revenue
FROM customer_shopping_behavior
GROUP BY gender;

-- which customer use discount but still spent more than average purchase amount
SELECT customer_id, purchase_amount 
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes' 
AND  purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping_behavior);

-- top 5 products with highest average review rating
SELECT  item_purchased AS products, ROUND(AVG(review_rating),2) AS average_rating
FROM customer_shopping_behavior
GROUP BY  item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- compare average purchase amount between standard and express shipping
SELECT shipping_type , 
AVG(purchase_amount) AS average_amount
FROM customer_shopping_behavior
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

 -- do subscribed customer spend more ? compare average spend and total revenue between
 -- subscriber and non subscriber

SELECT COUNT(customer_id) AS total_customer,
subscription_status, 
AVG(purchase_amount) AS average,
SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status;

-- which 5 product have highest percentage of purchases with discount applied
SELECT 
    item_purchased AS product,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS discount_percentage
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM (
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_behavior
) AS customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;

-- what are the top 3 most purchased products within each category

WITH item_counts AS (
		SELECT category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
        FROM customer_shopping_behavior
        GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Are customers who repeat buyers (more than 5 previous purchase) also likely to subscribe
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior
WHERE previous_purchases >=5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group

SELECT age_group, 
SUM(purchase_amount) AS revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY revenue DESC;




